### ISSUE TITLE
Support Gradle RunConfiguration

### ISSUE THREAD

**Issue by noproxy** [JetBrains/gradle-idea-ext-plugin#74]
At now, `GradleTask` is supported as `beforeRunTask` of the `Application` run configuration. That cannot produce an correct run configuration because it lacks of Main class.

I add gradle task like this：

```java
   configureByName(settings, "runConfigurations", RunConfigurationContainer.class, runConfigurations -> {
                runConfigurations.create("Upload Maven Library", Application.class, application -> {
                    application.setModuleName(project.getRootProject().getName());
                    application.beforeRun(beforeRun -> {
                        beforeRun.create("assemble", GradleTask.class, gradleTask -> {
                            gradleTask.setTask( getPublishTask());
                        });
                    });
                });
            });
```

And I will get the run configurations:

![image](https://user-images.githubusercontent.com/5850903/53873737-eaea9100-403b-11e9-91b5-8ff2f0d04646.png)

I think I need to generate the true Gradle Run Configurations：
 
![image](https://user-images.githubusercontent.com/5850903/53873799-0eadd700-403c-11e9-9f42-4d033e2309db.png)

**Comment by breandan** [comment]
I also encountered this issue and reported it in #47, but the issue was closed for some reason. The way [`GradleTask`](https://github.com/JetBrains/gradle-idea-ext-plugin/blob/423e75ff40e209f963eb84d24f942bfe1f47faca/src/main/groovy/org/jetbrains/gradle/ext/RunConfigurations.groovy#L145:L158) is currently defined, this cannot possibly work as described in [v0.1 of the DSL spec](https://github.com/JetBrains/gradle-idea-ext-plugin/wiki/DSL-spec-v.-0.1#runconfigurations), and I'm having difficulty understanding how [`"Gradle run configuration name"(Gradle)`](https://github.com/JetBrains/gradle-idea-ext-plugin/issues/47#issuecomment-444874581) could work as described by @nskvortsov. Either the docs need to be updated, or a new DSL endpoint (e.g. `GradleRC`) needs to be defined that extends [`BaseRunConfiguration`](https://github.com/JetBrains/gradle-idea-ext-plugin/blob/423e75ff40e209f963eb84d24f942bfe1f47faca/src/main/groovy/org/jetbrains/gradle/ext/RunConfigurations.groovy#L47) similar to [`TestNG`](https://github.com/JetBrains/gradle-idea-ext-plugin/blob/423e75ff40e209f963eb84d24f942bfe1f47faca/src/main/groovy/org/jetbrains/gradle/ext/RunConfigurations.groovy#L174) and [`Application`](https://github.com/JetBrains/gradle-idea-ext-plugin/blob/423e75ff40e209f963eb84d24f942bfe1f47faca/src/main/groovy/org/jetbrains/gradle/ext/RunConfigurations.groovy#L73).

**Comment by nskvortsov** [comment]
@breandan @noproxy  I apologize for the confusion. I was sure the Gradle run configuration support was already implemented and did not check it properly.  Indeed, there is no Gradle run configuration support at the moment (v 0.5, Ideal 2019.1)
I will re-open #47 and check it is properly implemented.
